language: python

python:
  - "3.6"

services:
  - postgresql

addons:
  firefox: "52.0esr"

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.15.0/geckodriver-v0.15.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.15.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

install:
  - pip install -r requirements/ci.txt

before_script:
  # postgresql
  - psql -c "CREATE ROLE dictlv" -U postgres
  - psql -c "ALTER ROLE dictlv CREATEDB" -U postgres
  - psql -c "ALTER ROLE dictlv LOGIN" -U postgres
  - psql -c "CREATE DATABASE translations;" -U postgres
  # xvfb
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - python manage.py test translations --settings=dictlv.settings.local
  - python manage.py test functional_tests --settings=dictlv.settings.local