language: python

python:
  - "3.6"

services:
  - postgresql

install:
  - pip install -r requirements/ci.txt

before_script:
  - psql -c "CREATE ROLE dictlv" -U postgres
  - psql -c "ALTER ROLE dictlv CREATEDB" -U postgres
  - psql -c "ALTER ROLE dictlv LOGIN" -U postgres
  - psql -c "CREATE DATABASE translations;" -U postgres

script:
  - python manage.py test translations
  - python manage.py test functional_tests